[Fix #233] Add more trailing comma rules
datarockets/datarockets-style pull request #246
Opened 2021-02-09 10:47 UTC by paydaylight

### Added more trailing comma cops as in [#218](https://github.com/datarockets/datarockets-style/issues/218):
* Added `EnforcedStyleForMultiline: comma`  for `Style/TrailingCommaInArguments` and `Style/TrailingCommaInArrayLiteral`.
* Did not enable `Style/TrailingCommaInBlockArgs` because of safety warnings and unsure usage purpose

Before you submit a pull request, please make sure you have to follow:

- [ ] read and know items from the [Contributing Guide](https://github.com/datarockets/datarockets-style/blob/master/CONTRIBUTING.md#pull-requests)
- [ ] add a description of the problem you're trying to solve (short summary from related issue)
- [ ] verified that cops are ordered by alphabet
- [ ] add a note to the style guide docs (if it needs)
- [ ] add a note to the changelog file
- [ ] the commit message contains the number of the related issue (if it presents)
  and word `Fix` if this PR closes related issue
- [ ] squash all commits before submitting to review

2021-02-09 12:27 UTC, texpert approved these changes

2021-02-10 08:08 UTC, roman-dubrovsky reviewed
Can you rebase this PR to the latest master?

2021-02-10 08:08 UTC, roman-dubrovsky commented on CHANGELOG.md
> +* [#233](https://github.com/datarockets/datarockets-style/issues/233) Setup `EnforcedStyleForMultiline` for `Style/TrailingCommaInArguments` and `Style/TrailingCommaInArrayLiteral` rules. ([@paydayli
```suggestion
* [#233](https://github.com/datarockets/datarockets-style/issues/233) Setup `EnforcedStyleForMultiline` for `Style/TrailingCommaInArguments` and `Style/TrailingCommaInArrayLiteral` rules. ([@paydaylight][])
```

2021-02-10 08:08 UTC, roman-dubrovsky commented
> Did not enable Style/TrailingCommaInBlockArgs because of safety warnings and unsure usage purpose

agreed about `unsure usage purpose` but @paydaylight what did you mean when wrote `because of safety warnings` ?

2021-02-10 14:12 UTC, paydaylight commented
@roman-dubrovsky cop is labeled `unsafe`, that's what I meant

2021-02-10 17:59 UTC, roman-dubrovsky requested changes

2021-02-10 17:59 UTC, roman-dubrovsky commented on CHANGELOG.md
> +* [#233](https://github.com/datarockets/datarockets-style/issues/233) Setup `EnforcedStyleForMultiline` for `Style/TrailingCommaInArguments` and `Style/TrailingCommaInArrayLiteral` rules. ([@paydayli
```suggestion
### Changed

* [#233](https://github.com/datarockets/datarockets-style/issues/233) Setup `EnforcedStyleForMultiline` for `Style/TrailingCommaInArguments` and `Style/TrailingCommaInArrayLiteral` rules. ([@paydaylight][])
```

2021-02-10 17:59 UTC, roman-dubrovsky commented on lib/datarockets_style/version.rb
> +  VERSION = "1.0.0".freeze
same about version

2021-02-11 08:33 UTC, paydaylight commented
@roman-dubrovsky fixed

2021-02-15 13:32 UTC, roman-dubrovsky approved these changes

2021-02-16 06:58 UTC, merged